---
- name: install prerequisites
  apt:
    name: software-properties-common
    update_cache: yes
    state: present

- name: add deadsnakes repo
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: install python
  apt:
    name: "python{{ python_version }}"
    state: present
